server:
  port: 8082

spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.spiderman.xzf:3306/scheduler?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: root
    password: root
  redis:
    host: redis.spiderman.xzf
    port: 6379
    database: 0
    timeout: 210s
  session:
    store-type: redis

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 10000

xzf:
  spiderman:
    curator:
      connectionString: zk.spiderman.xzf:2181
    common:
      cookie:
        domain: spiderman.xzf

