version: '3'
 
services:
    mysql:
        container_name: mysql5.7
        image: mysql:5.7
 
        ports:
          - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: "root"
        command:
          --wait_timeout=31536000
          --interactive_timeout=31536000
          --max_connections=1000
          --character-set-server=utf8mb4
          --collation-server=utf8mb4_unicode_ci
        volumes:
          - "./mysql/data:/var/lib/mysql"
          - "./mysql/config:/etc/mysql/conf.d"
          - "./mysql/mysql.conf.d:/etc/mysql/mysql.conf.d"

    redis:
        container_name: redis5
        # 指定镜像
        image: redis:5
        ports:
          # 端口映射
          - 6379:6379
        volumes:
          # 目录映射
          - "./redis/conf:/usr/local/etc/redis"
          - "./redis/data:/data"
        command:
          # 执行的命令
          redis-server
          
          
    zookeeper:
        container_name: zookeeper
        image: zookeeper
        ports:
            - 2181:2181
        environment:
            ZOO_MY_ID: 1
        volumes:
            - "./zookeeper/data:/data"
            - "./zookeeper/datalog:/datalog"
   
    nacos:
      image: nacos/nacos-server:latest
      container_name: nacos-standalone-mysql
      env_file:
         - ./nacos/env/nacos-standlone-mysql.env
      volumes:
         - ./nacos/standalone-logs/:/home/nacos/logs
         - ./nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
      ports:
        - "8848:8848"
        - "9555:9555"
      depends_on:
        - mysql
      restart: on-failure

    kafka:
      image: wurstmeister/kafka
      container_name: kafka
      ports:
        - 9092:9092
      environment:
        KAFKA_ADVERTISED_HOST_NAME: 192.168.31.156                     ## 修改:宿主机IP
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.31.156:9092    ## 修改:宿主机IP
        KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
        KAFKA_ADVERTISED_PORT: 9092
        KAFKA_BROKER_ID: 1
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        JMX_PORT: 9999
      volumes:
        - ./kafka/data:/kafka
        - ./kafka/config:/opt/kafka/config
      depends_on:
        - zookeeper

#    kafka-manager:
#      image: kafka-manager:xzf
#      environment:
#        ZK_HOSTS: zookeeper:2181
#      ports:
#        - "9000:9000"
#      depends_on:
#        - kafka


    mongo:
      image: mongo
      volumes:
        - "./mongodb/db:/data/db"
        - "./mongodb/mongod.conf.orig:/etc/mongod.conf.orig"
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: 123456
