server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: spider-man-admin
          uri: lb://spider-man-admin
          predicates:
            - Path=/api/admin/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),  /$\{segment}
        - id: spider-man-scheduler
          uri: lb://spider-man-scheduler
          predicates:
            - Path=/api/scheduler/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),  /$\{segment}
        - id: spider-man-worker
          uri: lb://spider-man-worker
          predicates:
            - Path=/api/worker/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),  /$\{segment}

