server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.spiderman.xzf:3306/worker?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: root
    password: root
  redis:
    host: redis.spiderman.xzf
    port: 6379
    database: 0
    timeout: 120s
  kafka:
    bootstrap-servers: kafka.spiderman.xzf:9092
    producer:
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  session:
    store-type: redis

xzf:
  spiderman:
    worker:
      spider-blocking-scheduler:
        default-timeout-seconds: 30
      spider-slave-pool:
        core-threads: 2
        pool-threads: 10
        keep-alive-time-seconds: 60
    curator:
      connectionString: zk.spiderman.xzf:2181
    common:
      cookie:
        domain: spiderman.xzf

